# Generated by Django 4.2 on 2023-04-13 07:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("elaboration", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentQualification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("elaboration", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("elaboration", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentTrait",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("elaboration", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PromptType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="WorldBuildingAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("subtr", models.TextField(blank=True)),
                ("elaboration", models.TextField(blank=True)),
                ("goals", models.ManyToManyField(blank=True, to="phusis.agentgoal")),
                (
                    "personality",
                    models.ManyToManyField(blank=True, to="phusis.agenttrait"),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(blank=True, to="phusis.agentqualification"),
                ),
                ("roles", models.ManyToManyField(blank=True, to="phusis.agentrole")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebSearchAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("subtr", models.TextField(blank=True)),
                ("elaboration", models.TextField(blank=True)),
                ("goals", models.ManyToManyField(blank=True, to="phusis.agentgoal")),
                (
                    "personality",
                    models.ManyToManyField(blank=True, to="phusis.agenttrait"),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(blank=True, to="phusis.agentqualification"),
                ),
                ("roles", models.ManyToManyField(blank=True, to="phusis.agentrole")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThemeExploringAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("subtr", models.TextField(blank=True)),
                ("elaboration", models.TextField(blank=True)),
                ("goals", models.ManyToManyField(blank=True, to="phusis.agentgoal")),
                (
                    "personality",
                    models.ManyToManyField(blank=True, to="phusis.agenttrait"),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(blank=True, to="phusis.agentqualification"),
                ),
                ("roles", models.ManyToManyField(blank=True, to="phusis.agentrole")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StructuralAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("subtr", models.TextField(blank=True)),
                ("elaboration", models.TextField(blank=True)),
                ("goals", models.ManyToManyField(blank=True, to="phusis.agentgoal")),
                (
                    "personality",
                    models.ManyToManyField(blank=True, to="phusis.agenttrait"),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(blank=True, to="phusis.agentqualification"),
                ),
                ("roles", models.ManyToManyField(blank=True, to="phusis.agentrole")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResearchAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("subtr", models.TextField(blank=True)),
                ("elaboration", models.TextField(blank=True)),
                ("goals", models.ManyToManyField(blank=True, to="phusis.agentgoal")),
                (
                    "personality",
                    models.ManyToManyField(blank=True, to="phusis.agenttrait"),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(blank=True, to="phusis.agentqualification"),
                ),
                ("roles", models.ManyToManyField(blank=True, to="phusis.agentrole")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QualityEvaluationAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("subtr", models.TextField(blank=True)),
                ("elaboration", models.TextField(blank=True)),
                ("goals", models.ManyToManyField(blank=True, to="phusis.agentgoal")),
                (
                    "personality",
                    models.ManyToManyField(blank=True, to="phusis.agenttrait"),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(blank=True, to="phusis.agentqualification"),
                ),
                ("roles", models.ManyToManyField(blank=True, to="phusis.agentrole")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "prompt_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phusis.prompttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoeticsAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("subtr", models.TextField(blank=True)),
                ("elaboration", models.TextField(blank=True)),
                ("goals", models.ManyToManyField(blank=True, to="phusis.agentgoal")),
                (
                    "personality",
                    models.ManyToManyField(blank=True, to="phusis.agenttrait"),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(blank=True, to="phusis.agentqualification"),
                ),
                ("roles", models.ManyToManyField(blank=True, to="phusis.agentrole")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrchestrationAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("subtr", models.TextField(blank=True)),
                ("elaboration", models.TextField(blank=True)),
                ("goals", models.ManyToManyField(blank=True, to="phusis.agentgoal")),
                (
                    "personality",
                    models.ManyToManyField(blank=True, to="phusis.agenttrait"),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(blank=True, to="phusis.agentqualification"),
                ),
                ("roles", models.ManyToManyField(blank=True, to="phusis.agentrole")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InterdisciplinaryAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("subtr", models.TextField(blank=True)),
                ("elaboration", models.TextField(blank=True)),
                ("goals", models.ManyToManyField(blank=True, to="phusis.agentgoal")),
                (
                    "personality",
                    models.ManyToManyField(blank=True, to="phusis.agenttrait"),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(blank=True, to="phusis.agentqualification"),
                ),
                ("roles", models.ManyToManyField(blank=True, to="phusis.agentrole")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConflictAndResolutionAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("subtr", models.TextField(blank=True)),
                ("elaboration", models.TextField(blank=True)),
                ("goals", models.ManyToManyField(blank=True, to="phusis.agentgoal")),
                (
                    "personality",
                    models.ManyToManyField(blank=True, to="phusis.agenttrait"),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(blank=True, to="phusis.agentqualification"),
                ),
                ("roles", models.ManyToManyField(blank=True, to="phusis.agentrole")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompressionAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("subtr", models.TextField(blank=True)),
                ("elaboration", models.TextField(blank=True)),
                ("goals", models.ManyToManyField(blank=True, to="phusis.agentgoal")),
                (
                    "personality",
                    models.ManyToManyField(blank=True, to="phusis.agenttrait"),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(blank=True, to="phusis.agentqualification"),
                ),
                ("roles", models.ManyToManyField(blank=True, to="phusis.agentrole")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CharacterAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("subtr", models.TextField(blank=True)),
                ("elaboration", models.TextField(blank=True)),
                ("goals", models.ManyToManyField(blank=True, to="phusis.agentgoal")),
                (
                    "personality",
                    models.ManyToManyField(blank=True, to="phusis.agenttrait"),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(blank=True, to="phusis.agentqualification"),
                ),
                ("roles", models.ManyToManyField(blank=True, to="phusis.agentrole")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
