# Generated by Django 4.2 on 2023-04-13 19:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0003_concretenovellormodeldecorator"),
        ("phusis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcreteAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                (
                    "agent_type",
                    models.CharField(default="", editable=False, max_length=200),
                ),
                ("subtr", models.TextField(blank=True)),
                ("elaboration", models.TextField(blank=True)),
                ("goals", models.ManyToManyField(blank=True, to="phusis.agentgoal")),
                (
                    "novellor_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="noveller.concretenovellormodeldecorator",
                    ),
                ),
                (
                    "personality",
                    models.ManyToManyField(blank=True, to="phusis.agenttrait"),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(blank=True, to="phusis.agentqualification"),
                ),
                ("roles", models.ManyToManyField(blank=True, to="phusis.agentrole")),
            ],
            options={
                "db_table": "phusis_concrete_agent",
            },
        ),
    ]
