# Generated by Django 4.2 on 2023-04-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phusis", "0002_agentgoal_characteragent_compressionagent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentgoal",
            name="elaboration",
            field=models.TextField(blank=True),
        ),
    ]
