# Generated by Django 4.2 on 2023-04-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0002_script_agent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='content',
            new_name='script_content',
        ),
        migrations.AddField(
            model_name='agentcreatedagents',
            name='steps_taken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='characteragent',
            name='steps_taken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='concreteagent',
            name='steps_taken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conflictandresolutionagent',
            name='steps_taken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interdisciplinaryagent',
            name='steps_taken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='poeticsagent',
            name='steps_taken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='qualityevaluationagent',
            name='steps_taken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchagent',
            name='steps_taken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='structuralagent',
            name='steps_taken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='themeexploringagent',
            name='steps_taken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='useragent',
            name='steps_taken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='websearchagent',
            name='steps_taken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='worldbuildingagent',
            name='steps_taken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='CompressionAgent',
        ),
    ]
