# Generated by Django 4.2 on 2023-04-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileParagraph',
        ),
        migrations.RenameField(
            model_name='chatlog',
            old_name='repsonse',
            new_name='response',
        ),
    ]
