# Generated by Django 4.2 on 2023-05-11 06:41

from django.db import migrations, models
import django.db.models.deletion
import phusis.agent_engines
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteAbstractAgent',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('agent_type', models.CharField(default='phusis_agent', editable=False, max_length=200)),
                ('agent_system_prompt', models.TextField(blank=True)),
                ('class_display_name', models.CharField(default='', max_length=200)),
                ('steps_taken', models.JSONField(blank=True, default=list)),
                ('embedding_of_self', models.TextField(blank=True)),
                ('awake', models.BooleanField(default=False)),
                ('wake_up_message', models.TextField(blank=True, null=True)),
                ('compressed_wake_up_message', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(null=True)),
                ('origin_story', models.TextField(blank=True)),
                ('elaboration', models.TextField(blank=True)),
                ('llelle', models.TextField(blank=True)),
                ('malig', models.TextField(blank=True)),
                ('subtr', models.TextField(blank=True)),
                ('agent_created_traits', models.ManyToManyField(blank=True, to='phusis.agentcreatedtrait')),
                ('assignments_for_agent', models.ManyToManyField(blank=True, default=[], related_name='%(class)s_assigned_agents', to='phusis.agentassignment')),
                ('attitudes', models.ManyToManyField(blank=True, to='phusis.agentattitude')),
                ('beliefs', models.ManyToManyField(blank=True, to='phusis.agentbelief')),
                ('capabilities', models.ManyToManyField(blank=True, to='phusis.agentcapability')),
                ('chat_logs', models.ManyToManyField(blank=True, to='phusis.chatlog')),
                ('drives', models.ManyToManyField(blank=True, to='phusis.agentdrive')),
                ('favored_genre_combos', models.ManyToManyField(blank=True, to='phusis.agentfavoredgenrecombo')),
                ('favored_genres', models.ManyToManyField(blank=True, to='phusis.agentfavoredgenre')),
                ('favored_themes', models.ManyToManyField(blank=True, to='phusis.agentfavoredtheme')),
                ('fears', models.ManyToManyField(blank=True, to='phusis.agentfear')),
                ('goals', models.ManyToManyField(blank=True, to='phusis.agentgoal')),
                ('impersonations', models.ManyToManyField(blank=True, to='phusis.agentimpersonation')),
                ('inspirational_sources', models.ManyToManyField(blank=True, to='phusis.agentinspirationalsource')),
                ('personality_traits', models.ManyToManyField(blank=True, to='phusis.agentpersonalitytrait')),
                ('possible_locations', models.ManyToManyField(blank=True, to='phusis.agentlocation')),
                ('qualifications', models.ManyToManyField(blank=True, to='phusis.agentqualification')),
                ('roles', models.ManyToManyField(blank=True, to='phusis.agentrole')),
                ('strengths', models.ManyToManyField(blank=True, to='phusis.agentstrength')),
                ('writing_style', models.ManyToManyField(blank=True, to='phusis.agentwritingstyle')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, phusis.agent_engines.AbstractEngine),
        ),
        migrations.AddField(
            model_name='agentassignment',
            name='agent_for_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_for_assignment', to='phusis.concreteabstractagent'),
        ),
    ]
