# Generated by Django 4.2 on 2023-05-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentassignment',
            name='related_project_goal_steps',
            field=models.ManyToManyField(blank=True, default=[], related_name='project_goal_steps_for_agent_assignment', to='phusis.phusisprojectgoalstep'),
        ),
    ]
