# Generated by Django 4.2 on 2023-04-20 21:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeexploringagent',
            name='themes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
