# Generated by Django 4.2 on 2023-04-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteragent',
            old_name='favored_themes',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='compressionagentsingleton',
            old_name='favored_themes',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='conflictandresolutionagent',
            old_name='favored_themes',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='embeddingsagentsingleton',
            old_name='favored_themes',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='interdisciplinaryagent',
            old_name='favored_themes',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='orchestrationagent',
            old_name='favored_themes',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='poeticsagent',
            old_name='favored_themes',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='qualityevaluationagent',
            old_name='favored_themes',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='researchagent',
            old_name='favored_themes',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='structuralagent',
            old_name='favored_themes',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='themeexploringagent',
            old_name='favored_themes',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='useragentsingleton',
            old_name='favored_themes',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='websearchagentsingleton',
            old_name='favored_themes',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='worldbuildingagent',
            old_name='favored_themes',
            new_name='themes',
        ),
        migrations.RenameField(
            model_name='writingagent',
            old_name='favored_themes',
            new_name='themes',
        ),
    ]
