# Generated by Django 4.2 on 2023-04-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('noveller', '0002_initial'),
        ('phusis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbookrelationship',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noveller.book'),
        ),
        migrations.AddField(
            model_name='agentbookrelationship',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
