# Generated by Django 4.2 on 2023-04-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0003_concretenovellormodeldecorator"),
        ("phusis", "0003_remove_concreteagent_novellor_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concreteagent",
            name="is_concerned_with",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)sagents_concerned_with_this",
                to="noveller.concretenovellormodeldecorator",
            ),
        ),
        migrations.AlterField(
            model_name="concreteagent",
            name="is_influenced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)sagents_influenced_by_this",
                to="noveller.concretenovellormodeldecorator",
            ),
        ),
    ]
