# Generated by Django 4.2 on 2023-04-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0003_delete_fileparagraph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='compressed_prompt_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatlog',
            name='compressed_response_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
