# Generated by Django 4.2 on 2023-04-12 06:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("phusis", "0003_agentgoal_elaboration"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentQualification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("elaboration", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgentTrait",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("elaboration", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="agent",
            name="elaboration",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="subtr",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="introduction",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="personality",
            field=models.ManyToManyField(to="phusis.agenttrait"),
        ),
        migrations.AddField(
            model_name="agent",
            name="qualifications",
            field=models.ManyToManyField(to="phusis.agentqualification"),
        ),
    ]
