# Generated by Django 4.2 on 2023-05-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0003_concreteabstractagent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phusisprojectgoal',
            name='on_hold',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phusisprojectgoalstep',
            name='on_hold',
            field=models.BooleanField(default=True),
        ),
    ]
