# Generated by Django 4.2 on 2023-04-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phusisprojectgoal',
            name='steps',
            field=models.ManyToManyField(blank=True, to='phusis.phusisprojectgoalstep'),
        ),
    ]
