# Generated by Django 4.2 on 2023-04-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0002_rename_literarytraits_literarytrait'),
        ('phusis', '0003_rename_content_script_script_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAgent',
            new_name='UserAgentSingleton',
        ),
    ]
