# Generated by Django 4.2 on 2023-04-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0004_rename_useragent_useragentsingleton'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Script',
            new_name='AgentScriptModel',
        ),
    ]
