# Generated by Django 4.2 on 2023-04-28 20:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0004_alter_phusisprojectgoal_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phusisprojectattribute',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='phusisprojectgoal',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phusisprojectgoal',
            name='steps',
            field=models.ManyToManyField(blank=True, default=[], to='phusis.phusisprojectgoalstep'),
        ),
        migrations.AlterField(
            model_name='phusisprojectgoalstep',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='phusisprojectgoalstep',
            name='related_project_attributes',
            field=models.ManyToManyField(blank=True, default=[], related_name='project_attributes_for_project_goal_step', to='phusis.phusisprojectattribute'),
        ),
        migrations.CreateModel(
            name='AgentAssignment',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('assignment_str', models.TextField(blank=True, default='', null=True)),
                ('additional_assignment_instructions', models.TextField(blank=True, default='', null=True)),
                ('assignment_proj_att', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_attribute_for_agent_assignment', to='phusis.phusisprojectattribute')),
            ],
        ),
        migrations.AddField(
            model_name='characteragent',
            name='agent_assignments',
            field=models.ManyToManyField(blank=True, default=[], related_name='%(class)s_assignments', to='phusis.agentassignment'),
        ),
        migrations.AddField(
            model_name='conflictandresolutionagent',
            name='agent_assignments',
            field=models.ManyToManyField(blank=True, default=[], related_name='%(class)s_assignments', to='phusis.agentassignment'),
        ),
        migrations.AddField(
            model_name='interdisciplinaryagent',
            name='agent_assignments',
            field=models.ManyToManyField(blank=True, default=[], related_name='%(class)s_assignments', to='phusis.agentassignment'),
        ),
        migrations.AddField(
            model_name='orchestrationagent',
            name='agent_assignments',
            field=models.ManyToManyField(blank=True, default=[], related_name='%(class)s_assignments', to='phusis.agentassignment'),
        ),
        migrations.AddField(
            model_name='phusisprojectgoalstep',
            name='agent_assignments_for_step',
            field=models.ManyToManyField(blank=True, default=[], related_name='project_goal_steps_for_agent_assignment', to='phusis.agentassignment'),
        ),
        migrations.AddField(
            model_name='poeticsagent',
            name='agent_assignments',
            field=models.ManyToManyField(blank=True, default=[], related_name='%(class)s_assignments', to='phusis.agentassignment'),
        ),
        migrations.AddField(
            model_name='qualityevaluationagent',
            name='agent_assignments',
            field=models.ManyToManyField(blank=True, default=[], related_name='%(class)s_assignments', to='phusis.agentassignment'),
        ),
        migrations.AddField(
            model_name='researchagent',
            name='agent_assignments',
            field=models.ManyToManyField(blank=True, default=[], related_name='%(class)s_assignments', to='phusis.agentassignment'),
        ),
        migrations.AddField(
            model_name='structuralagent',
            name='agent_assignments',
            field=models.ManyToManyField(blank=True, default=[], related_name='%(class)s_assignments', to='phusis.agentassignment'),
        ),
        migrations.AddField(
            model_name='themeexploringagent',
            name='agent_assignments',
            field=models.ManyToManyField(blank=True, default=[], related_name='%(class)s_assignments', to='phusis.agentassignment'),
        ),
        migrations.AddField(
            model_name='useragentsingleton',
            name='agent_assignments',
            field=models.ManyToManyField(blank=True, default=[], related_name='%(class)s_assignments', to='phusis.agentassignment'),
        ),
        migrations.AddField(
            model_name='worldbuildingagent',
            name='agent_assignments',
            field=models.ManyToManyField(blank=True, default=[], related_name='%(class)s_assignments', to='phusis.agentassignment'),
        ),
        migrations.AddField(
            model_name='writingagent',
            name='agent_assignments',
            field=models.ManyToManyField(blank=True, default=[], related_name='%(class)s_assignments', to='phusis.agentassignment'),
        ),
    ]
