# Generated by Django 4.2 on 2023-04-21 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0004_agentfavoredgenrecombo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInspirationalSource',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('elaboration', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
