# Generated by Django 4.2 on 2023-04-20 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0004_writingagent_favored_genre_combinations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phusisscript',
            name='is_master_script',
        ),
    ]
