# Generated by Django 4.2 on 2023-04-12 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0004_agentqualification_agenttrait_agent_elaboration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteAgent',
            fields=[
                ('agent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.agent')),
            ],
            bases=('phusis.agent',),
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
