# Generated by Django 4.2 on 2023-04-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0005_remove_book_script_for_project'),
        ('phusis', '0005_remove_phusisscript_is_master_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteragent',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='compressionagentsingleton',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='conflictandresolutionagent',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='dynamicagent',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='embeddingsagentsingleton',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='interdisciplinaryagent',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='orchestrationagent',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='poeticsagent',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='qualityevaluationagent',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='researchagent',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='structuralagent',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='themeexploringagent',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='useragentsingleton',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='websearchagentsingleton',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='worldbuildingagent',
            name='script_for_agent',
        ),
        migrations.RemoveField(
            model_name='writingagent',
            name='script_for_agent',
        ),
        migrations.DeleteModel(
            name='PhusisScript',
        ),
    ]
