# Generated by Django 4.2 on 2023-05-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0005_remove_phusisprojectgoalstep_related_project_attributes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phusisprojectgoalstep',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='phusisprojectgoalstep',
            name='object_id',
        ),
        migrations.AddField(
            model_name='phusisprojectgoalstep',
            name='related_project_attribute_names',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
