# Generated by Django 4.2 on 2023-04-16 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0005_rename_script_agentscriptmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentcreatedagents',
            name='script',
        ),
        migrations.RemoveField(
            model_name='characteragent',
            name='script',
        ),
        migrations.RemoveField(
            model_name='concreteagent',
            name='script',
        ),
        migrations.RemoveField(
            model_name='conflictandresolutionagent',
            name='script',
        ),
        migrations.RemoveField(
            model_name='interdisciplinaryagent',
            name='script',
        ),
        migrations.RemoveField(
            model_name='poeticsagent',
            name='script',
        ),
        migrations.RemoveField(
            model_name='qualityevaluationagent',
            name='script',
        ),
        migrations.RemoveField(
            model_name='researchagent',
            name='script',
        ),
        migrations.RemoveField(
            model_name='structuralagent',
            name='script',
        ),
        migrations.RemoveField(
            model_name='themeexploringagent',
            name='script',
        ),
        migrations.RemoveField(
            model_name='useragentsingleton',
            name='script',
        ),
        migrations.RemoveField(
            model_name='websearchagent',
            name='script',
        ),
        migrations.RemoveField(
            model_name='worldbuildingagent',
            name='script',
        ),
        migrations.DeleteModel(
            name='AgentScriptModel',
        ),
    ]
