# Generated by Django 4.2 on 2023-04-17 00:55

from django.db import migrations, models
import django.db.models.deletion
import phusis.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0006_remove_agentcreatedagents_script_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_master_script', models.BooleanField(default=False)),
                ('script_content', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AddField(
            model_name='concreteagent',
            name='class_display_name',
            field=models.CharField(default='Phusis <django.db.models.fields.CharField> Agents', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='useragentsingleton',
            name='class_display_name',
            field=models.CharField(default='Phusis <django.db.models.fields.CharField> Agents', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='agentcreatedagents',
            name='agent_type',
            field=models.CharField(default='phusis_agent', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='concreteagent',
            name='agent_type',
            field=models.CharField(default='phusis_agent', editable=False, max_length=200),
        ),
        migrations.CreateModel(
            name='OrchestrationAgent',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('elaboration', models.TextField(blank=True)),
                ('orc_character_age', models.IntegerField(null=True)),
                ('orc_character_possible_locations', models.JSONField(blank=True, default=list)),
                ('orc_character_attitudes', models.JSONField(blank=True, default=list)),
                ('orc_character_strengths', models.JSONField(blank=True, default=list)),
                ('orc_character_drives', models.JSONField(blank=True, default=list)),
                ('orc_character_fears', models.JSONField(blank=True, default=list)),
                ('orc_character_beliefs', models.JSONField(blank=True, default=list)),
                ('orc_character_origin_story', models.TextField(blank=True)),
                ('orc_character_llelle', models.TextField(blank=True)),
                ('orc_character_malig', models.TextField(blank=True)),
                ('orc_character_subtr', models.TextField(blank=True)),
                ('agent_created_traits', models.JSONField(blank=True, default=list)),
                ('goals', models.ManyToManyField(blank=True, to='phusis.orcagentgoal')),
                ('orc_character_impersonations', models.ManyToManyField(blank=True, to='phusis.orcagentimpersonation')),
                ('orc_character_personality_traits', models.ManyToManyField(blank=True, to='phusis.orcagenttrait')),
                ('qualifications', models.ManyToManyField(blank=True, to='phusis.orcagentqualification')),
                ('roles', models.ManyToManyField(blank=True, to='phusis.orcagentrole')),
                ('script', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phusis.script')),
            ],
            bases=(models.Model, phusis.models.OrchestrationEngine),
        ),
        migrations.AddField(
            model_name='agentcreatedagents',
            name='script',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phusis.script'),
        ),
        migrations.AddField(
            model_name='characteragent',
            name='script',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phusis.script'),
        ),
        migrations.AddField(
            model_name='concreteagent',
            name='script',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concrete_agent_for_script', to='phusis.script'),
        ),
        migrations.AddField(
            model_name='conflictandresolutionagent',
            name='script',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phusis.script'),
        ),
        migrations.AddField(
            model_name='interdisciplinaryagent',
            name='script',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phusis.script'),
        ),
        migrations.AddField(
            model_name='poeticsagent',
            name='script',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phusis.script'),
        ),
        migrations.AddField(
            model_name='qualityevaluationagent',
            name='script',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phusis.script'),
        ),
        migrations.AddField(
            model_name='researchagent',
            name='script',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phusis.script'),
        ),
        migrations.AddField(
            model_name='structuralagent',
            name='script',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phusis.script'),
        ),
        migrations.AddField(
            model_name='themeexploringagent',
            name='script',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phusis.script'),
        ),
        migrations.AddField(
            model_name='useragentsingleton',
            name='script',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phusis.script'),
        ),
        migrations.AddField(
            model_name='websearchagent',
            name='script',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phusis.script'),
        ),
        migrations.AddField(
            model_name='worldbuildingagent',
            name='script',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phusis.script'),
        ),
    ]
