# Generated by Django 4.2 on 2023-05-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0006_remove_phusisprojectgoalstep_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phusisprojectgoalstep',
            name='agent_assignments_for_step',
            field=models.ManyToManyField(blank=True, default=list, related_name='agent_assignments_for_step', to='phusis.agentassignment'),
        ),
        migrations.AlterField(
            model_name='phusisprojectgoalstep',
            name='related_project_attribute_names',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
