# Generated by Django 4.2 on 2023-04-17 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0007_script_concreteagent_class_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useragentsingleton',
            name='class_display_name',
        ),
    ]
