# Generated by Django 4.2 on 2023-05-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0007_phusisprojectgoalstep_agent_assignments_for_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreteabstractagent',
            name='type_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orchestrationagent',
            name='type_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='useragentsingleton',
            name='type_description',
            field=models.TextField(blank=True),
        ),
    ]
