# Generated by Django 4.2 on 2023-04-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0008_remove_useragentsingleton_class_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteagent',
            name='class_display_name',
            field=models.CharField(default='Phusis <django.db.models.fields.CharField> Agent', editable=False, max_length=200),
        ),
    ]
