# Generated by Django 4.2 on 2023-05-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('phusis', '0009_dynamicagent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentassignment',
            old_name='object_id',
            new_name='agent_object_id',
        ),
        migrations.RemoveField(
            model_name='agentassignment',
            name='agent_for_assignment',
        ),
        migrations.RemoveField(
            model_name='agentassignment',
            name='content_type',
        ),
        migrations.AddField(
            model_name='agentassignment',
            name='agent_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_agentassignments', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='agentassignment',
            name='assignment_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_agentassignments', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='agentassignment',
            name='assignment_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
