# Generated by Django 4.2 on 2023-05-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('phusis', '0011_rename_awake_concreteabstractagent_is_awake_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentassignment',
            old_name='assignment_str',
            new_name='additional_instructions',
        ),
        migrations.RenameField(
            model_name='agentassignment',
            old_name='agent_content_type',
            new_name='assigned_agent_content_type',
        ),
        migrations.RenameField(
            model_name='agentassignment',
            old_name='agent_object_id',
            new_name='assigned_agent_object_id',
        ),
        migrations.RenameField(
            model_name='agentassignment',
            old_name='assignment_object_id',
            new_name='assigned_phusis_attribute_object_id',
        ),
        migrations.RemoveField(
            model_name='agentassignment',
            name='assignment_content_type',
        ),
        migrations.RemoveField(
            model_name='agentassignment',
            name='related_project_goal_steps',
        ),
        migrations.AddField(
            model_name='agentassignment',
            name='assigned_phusis_attribute_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_attassignments', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='agentassignment',
            name='assigned_phusis_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phusis.phusisprojectgoalstep'),
        ),
    ]
