# Generated by Django 4.2 on 2023-04-27 16:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('phusis', '0002_initial'),
        ('noveller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundEvent',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('order_in_story_events', models.IntegerField(blank=True, null=True)),
                ('order_in_narrative_telling', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='BackgroundResearch',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('research', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('project_type', models.CharField(default='Book', max_length=200)),
                ('project_user_input', models.TextField(blank=True, default='')),
                ('project_workspace', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('orc_agent_set_objectives', models.TextField(blank=True, default='')),
                ('project_embedding', models.TextField(blank=True)),
                ('from_app', models.CharField(default='noveller', max_length=200)),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('expose_rest', models.BooleanField(default=True)),
                ('agents_for_project', models.ManyToManyField(related_name='projects_assigned_to', through='phusis.AgentBookRelationship', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('chapter_num', models.IntegerField(null=True)),
                ('chapter_goals', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['chapter_num'],
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='ChapterPart',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('part_num', models.IntegerField(null=True)),
                ('part_goals', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['for_chapter__chapter_num', 'part_num'],
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='ChapterPartSummary',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('chapter_part_summary', models.TextField(blank=True, null=True)),
                ('for_chapter_part', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noveller.chapterpart')),
            ],
            options={
                'ordering': ['for_chapter_part__for_chapter__chapter_num', 'for_chapter_part__part_num'],
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('age_at_start', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.CharField(blank=True, max_length=200, null=True)),
                ('sexuality', models.CharField(blank=True, max_length=200, null=True)),
                ('origin', models.TextField(blank=True, null=True)),
                ('permanent_characteristics', models.TextField(blank=True, null=True)),
                ('character_arc', models.TextField(blank=True, null=True)),
                ('books', models.ManyToManyField(to='noveller.book')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='CharacterAppearance',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('distinguishing_features', models.TextField(null=True)),
                ('eyes', models.CharField(max_length=200, null=True)),
                ('hair', models.CharField(max_length=200, null=True)),
                ('face', models.CharField(max_length=200, null=True)),
                ('build', models.CharField(blank=True, max_length=200, null=True)),
                ('movement', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['character_version__for_character__name', 'character_version__version_num'],
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='CharacterAppearanceModifiers',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('clothing', models.TextField(blank=True, null=True)),
                ('hair_head_options', models.TextField(blank=True, null=True)),
                ('perfume', models.CharField(blank=True, max_length=200, null=True)),
                ('makeup', models.CharField(blank=True, max_length=200, null=True)),
                ('shaving', models.CharField(blank=True, max_length=200, null=True)),
                ('hygiene', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='CharacterBelief',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='CharacterDrive',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='CharacterFear',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='CharacterInternalConflict',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('age_started', models.IntegerField(null=True)),
                ('relationship_descriptors', models.TextField(null=True)),
            ],
            options={
                'ordering': ['relationship_from__for_character__name', 'relationship_to__for_character__name'],
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='CharacterTrait',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='CharacterVersion',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('version_num', models.IntegerField(null=True)),
                ('age_at_start', models.IntegerField(blank=True, null=True)),
                ('age_at_end', models.IntegerField(blank=True, null=True)),
                ('preferred_weapon', models.CharField(blank=True, max_length=200, null=True)),
                ('subter', models.CharField(blank=True, max_length=200, null=True)),
                ('appearance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noveller.characterappearance')),
                ('beliefs', models.ManyToManyField(blank=True, to='noveller.characterbelief')),
                ('drives', models.ManyToManyField(blank=True, to='noveller.characterdrive')),
                ('fears', models.ManyToManyField(blank=True, to='noveller.characterfear')),
                ('for_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noveller.character')),
                ('internal_conflicts', models.ManyToManyField(blank=True, to='noveller.characterinternalconflict')),
            ],
            options={
                'ordering': ['for_character__name'],
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='DeeperBackgroundResearchTopic',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('members', models.ManyToManyField(blank=True, to='noveller.characterversion')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('file_location', models.CharField(max_length=255, null=True)),
                ('file_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='LiteraryImagery',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='LiteraryInspiration',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='LiteraryMood',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='LiteraryStyleGuide',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('style_guide', models.TextField(blank=True, null=True)),
                ('compressed_sg', models.TextField(blank=True, null=True)),
                ('writing_samples', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='LiterarySymbolism',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='LiteraryTheme',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='LiteraryTone',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='LiteraryTrait',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='NarrativePerspective',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='PlotEvent',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('order_in_story_events', models.IntegerField(blank=True, null=True)),
                ('order_in_narrative_telling', models.IntegerField(blank=True, null=True)),
                ('is_climax_of_plot', models.BooleanField(blank=True, null=True)),
                ('for_plot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plots_events', to='noveller.plot')),
                ('foreshadowing', models.ManyToManyField(blank=True, related_name='SubPlotEvent', to='noveller.plotevent')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='StoryPacing',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='SubPlot',
            fields=[
                ('plot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='noveller.plot')),
            ],
            options={
                'ordering': ['sub_plot_of__name', 'name'],
            },
            bases=('noveller.plot',),
        ),
        migrations.CreateModel(
            name='StoryTeller',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('character_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noveller.characterversion')),
                ('lit_style_guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noveller.literarystyleguide')),
            ],
            options={
                'ordering': ['character_version__for_character__name'],
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('general_setting', models.TextField(blank=True)),
                ('background_events', models.ManyToManyField(blank=True, to='noveller.backgroundevent')),
                ('background_research', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noveller.backgroundresearch')),
                ('books', models.ManyToManyField(blank=True, to='noveller.book')),
                ('factions', models.ManyToManyField(blank=True, to='noveller.faction')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.AddField(
            model_name='plot',
            name='events_of_plot',
            field=models.ManyToManyField(blank=True, to='noveller.plotevent'),
        ),
        migrations.AddField(
            model_name='plot',
            name='plot_for_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_plots', to='noveller.book'),
        ),
        migrations.AddField(
            model_name='literarystyleguide',
            name='avoid',
            field=models.ManyToManyField(blank=True, related_name='litstyleguide_avoid', to='noveller.literarytrait'),
        ),
        migrations.AddField(
            model_name='literarystyleguide',
            name='imagery',
            field=models.ManyToManyField(blank=True, to='noveller.literaryimagery'),
        ),
        migrations.AddField(
            model_name='literarystyleguide',
            name='inspirations',
            field=models.ManyToManyField(blank=True, to='noveller.literaryinspiration'),
        ),
        migrations.AddField(
            model_name='literarystyleguide',
            name='perspective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noveller.narrativeperspective'),
        ),
        migrations.AddField(
            model_name='literarystyleguide',
            name='symbolism',
            field=models.ManyToManyField(blank=True, to='noveller.literarysymbolism'),
        ),
        migrations.AddField(
            model_name='literarystyleguide',
            name='tone',
            field=models.ManyToManyField(blank=True, to='noveller.literarytone'),
        ),
        migrations.AddField(
            model_name='literarystyleguide',
            name='traits',
            field=models.ManyToManyField(blank=True, related_name='litstyleguide_traits', to='noveller.literarytrait'),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='lit_style_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noveller.literarystyleguide'),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='locations',
            field=models.ManyToManyField(blank=True, to='noveller.location'),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='often_perceived_as',
            field=models.ManyToManyField(blank=True, related_name='often_perceived_as', to='noveller.charactertrait'),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='other_aspects',
            field=models.ManyToManyField(blank=True, related_name='other_aspects', to='noveller.charactertrait'),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='relationships',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noveller.characterrelationship'),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='setting_based_appearance_modifier_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noveller.characterappearancemodifiers'),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='strengths',
            field=models.ManyToManyField(blank=True, related_name='strengths', to='noveller.charactertrait'),
        ),
        migrations.AddField(
            model_name='characterversion',
            name='weaknesses',
            field=models.ManyToManyField(blank=True, related_name='weaknesses', to='noveller.charactertrait'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='relationship_from',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_relationship', to='noveller.characterversion'),
        ),
        migrations.AddField(
            model_name='characterrelationship',
            name='relationship_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_relationship', to='noveller.characterversion'),
        ),
        migrations.CreateModel(
            name='CharacterRelatedSettingTopic',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('rights', models.TextField(blank=True, null=True)),
                ('attitudes', models.TextField(blank=True, null=True)),
                ('leisure', models.TextField(blank=True, null=True)),
                ('food', models.TextField(blank=True, null=True)),
                ('work', models.TextField(blank=True, null=True)),
                ('social_life', models.TextField(blank=True, null=True)),
                ('appearance_modifiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noveller.characterappearancemodifiers')),
                ('character_in_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noveller.setting')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.AddField(
            model_name='characterappearance',
            name='character_version',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appearance_for_character_version', to='noveller.characterversion'),
        ),
        migrations.AddField(
            model_name='character',
            name='representative_of',
            field=models.ManyToManyField(blank=True, to='noveller.literarytheme'),
        ),
        migrations.AddField(
            model_name='character',
            name='versions',
            field=models.ManyToManyField(blank=True, related_name='version_of_character', to='noveller.characterversion'),
        ),
        migrations.CreateModel(
            name='ChapterPartSummaryItem',
            fields=[
                ('phusisprojectattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phusis.phusisprojectattribute')),
                ('elaboration', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('order_in_part', models.IntegerField(blank=True, default=0, null=True)),
                ('for_chapter_part_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noveller.chapterpartsummary')),
            ],
            options={
                'ordering': ['for_chapter_part_summary__for_chapter_part__for_chapter__book', 'for_chapter_part_summary__for_chapter_part__for_chapter__chapter_num', 'for_chapter_part_summary__for_chapter_part__part_num', 'order_in_part'],
            },
            bases=('phusis.phusisprojectattribute',),
        ),
        migrations.AddField(
            model_name='chapterpartsummary',
            name='pacing',
            field=models.ManyToManyField(blank=True, to='noveller.storypacing'),
        ),
        migrations.AddField(
            model_name='chapterpartsummary',
            name='part_summary_items',
            field=models.ManyToManyField(blank=True, related_name='chapter_part_summary_items', to='noveller.chapterpartsummaryitem'),
        ),
        migrations.AddField(
            model_name='chapterpartsummary',
            name='themes',
            field=models.ManyToManyField(blank=True, to='noveller.literarytheme'),
        ),
        migrations.AddField(
            model_name='chapterpart',
            name='chapter_part_summary',
            field=models.ManyToManyField(blank=True, to='noveller.chapterpartsummary'),
        ),
        migrations.AddField(
            model_name='chapterpart',
            name='character_versions',
            field=models.ManyToManyField(blank=True, to='noveller.characterversion'),
        ),
        migrations.AddField(
            model_name='chapterpart',
            name='factions',
            field=models.ManyToManyField(blank=True, to='noveller.faction'),
        ),
        migrations.AddField(
            model_name='chapterpart',
            name='for_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_parts', to='noveller.chapter'),
        ),
        migrations.AddField(
            model_name='chapterpart',
            name='locations',
            field=models.ManyToManyField(blank=True, to='noveller.location'),
        ),
        migrations.AddField(
            model_name='chapterpart',
            name='storyteller_of_part',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noveller.storyteller'),
        ),
        migrations.AddField(
            model_name='chapterpart',
            name='themes',
            field=models.ManyToManyField(blank=True, to='noveller.literarytheme'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_draft_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noveller.file'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_in_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_characters', to='noveller.book'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='parts_for_chapter',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='noveller.chapterpart'),
        ),
        migrations.AddField(
            model_name='book',
            name='chapters',
            field=models.ManyToManyField(blank=True, related_name='books_chapters', to='noveller.chapter'),
        ),
        migrations.AddField(
            model_name='book',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='characters_book_characters', to='noveller.character'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='book_genres', to='noveller.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='goals_for_project',
            field=models.ManyToManyField(blank=True, to='phusis.phusisprojectgoal'),
        ),
        migrations.AddField(
            model_name='book',
            name='plots',
            field=models.ManyToManyField(blank=True, related_name='books_events', to='noveller.plot'),
        ),
        migrations.AddField(
            model_name='book',
            name='project_attributes',
            field=models.ManyToManyField(blank=True, null=True, to='phusis.phusisprojectattribute'),
        ),
        migrations.AddField(
            model_name='book',
            name='settings',
            field=models.ManyToManyField(blank=True, related_name='book_settings', to='noveller.setting'),
        ),
        migrations.AddField(
            model_name='book',
            name='target_audiences',
            field=models.ManyToManyField(blank=True, related_name='book_audiences', to='noveller.targetaudience'),
        ),
        migrations.AddField(
            model_name='book',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='book_themes', to='noveller.literarytheme'),
        ),
        migrations.AddField(
            model_name='backgroundresearch',
            name='deeper_research_topics',
            field=models.ManyToManyField(blank=True, to='noveller.deeperbackgroundresearchtopic'),
        ),
        migrations.CreateModel(
            name='SubPlotEvent',
            fields=[
                ('plotevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='noveller.plotevent')),
                ('subplot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subplots_events', to='noveller.subplot')),
            ],
            options={
                'ordering': ['order_in_story_events'],
            },
            bases=('noveller.plotevent',),
        ),
        migrations.AddField(
            model_name='subplot',
            name='events_of_subplot',
            field=models.ManyToManyField(blank=True, related_name='subplots_events', to='noveller.subplotevent'),
        ),
        migrations.AddField(
            model_name='subplot',
            name='sub_plot_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plots_subplot', to='noveller.plot'),
        ),
    ]
