# Generated by Django 4.2 on 2023-04-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiteraryTraits',
            new_name='LiteraryTrait',
        ),
    ]
