# Generated by Django 4.2 on 2023-04-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0004_alter_phusisprojectgoal_steps'),
        ('noveller', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='orc_agent_set_objectives',
            new_name='orc_agent_set_goals_str',
        ),
        migrations.AlterField(
            model_name='book',
            name='project_attributes',
            field=models.ManyToManyField(blank=True, to='phusis.phusisprojectattribute'),
        ),
    ]
