# Generated by Django 4.2 on 2023-05-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='order_in_narrative_telling',
            new_name='order_in_plot',
        ),
        migrations.RemoveField(
            model_name='book',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='order_in_story_events',
        ),
        migrations.AlterField(
            model_name='character',
            name='character_arc',
            field=models.TextField(blank=True, default='not yet set', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, default='not yet set', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='origin',
            field=models.TextField(blank=True, default='not yet set', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='permanent_characteristics',
            field=models.TextField(blank=True, default='not yet set', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='sex',
            field=models.CharField(blank=True, default='not yet set', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='sexuality',
            field=models.CharField(blank=True, default='not yet set', max_length=200, null=True),
        ),
    ]
