# Generated by Django 4.2 on 2023-04-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0002_alter_appearance_id_alter_appearancemodifiers_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storyevent",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_events",
                to="noveller.book",
            ),
        ),
    ]
