# Generated by Django 4.2 on 2023-04-13 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0002_alter_bgevent_options_alter_bgresearch_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcreteNovellorModelDecorator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("elaboration", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "noveller_concrete_novellor_model_decorator",
            },
        ),
    ]
