# Generated by Django 4.2 on 2023-05-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterversion',
            name='relationships',
            field=models.ManyToManyField(blank=True, to='noveller.characterrelationship'),
        ),
    ]
