# Generated by Django 4.2 on 2023-04-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phusis', '0002_initial'),
        ('noveller', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='agents_for_project',
            field=models.ManyToManyField(related_name='projects_assigned_to', through='phusis.AgentBookRelationship', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='book',
            name='chapters',
            field=models.ManyToManyField(blank=True, related_name='books_chapters', to='noveller.chapter'),
        ),
        migrations.AddField(
            model_name='book',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='characters_book_characters', to='noveller.character'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='book_genres', to='noveller.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='plots',
            field=models.ManyToManyField(blank=True, related_name='books_events', to='noveller.plot'),
        ),
        migrations.AddField(
            model_name='book',
            name='settings',
            field=models.ManyToManyField(blank=True, related_name='book_settings', to='noveller.setting'),
        ),
        migrations.AddField(
            model_name='book',
            name='target_audiences',
            field=models.ManyToManyField(blank=True, related_name='book_audiences', to='noveller.targetaudience'),
        ),
        migrations.AddField(
            model_name='book',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='book_themes', to='noveller.literarytheme'),
        ),
        migrations.AddField(
            model_name='backgroundresearch',
            name='deeper_research_topics',
            field=models.ManyToManyField(blank=True, to='noveller.deeperbackgroundresearchtopic'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='character_version',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appearance_for_character_version', to='noveller.characterversion'),
        ),
        migrations.AddField(
            model_name='subplotevent',
            name='subplot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subplots_events', to='noveller.subplot'),
        ),
        migrations.AddField(
            model_name='subplot',
            name='events_of_subplot',
            field=models.ManyToManyField(blank=True, related_name='subplots_events', to='noveller.subplotevent'),
        ),
        migrations.AddField(
            model_name='subplot',
            name='sub_plot_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plots_subplot', to='noveller.plot'),
        ),
    ]
