# Generated by Django 4.2 on 2023-04-24 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='chapters',
            field=models.ManyToManyField(blank=True, null=True, related_name='books_chapters', to='noveller.chapter'),
        ),
        migrations.AlterField(
            model_name='book',
            name='characters',
            field=models.ManyToManyField(blank=True, null=True, related_name='characters_book_characters', to='noveller.character'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_genres', to='noveller.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='plots',
            field=models.ManyToManyField(blank=True, null=True, related_name='books_events', to='noveller.plot'),
        ),
        migrations.AlterField(
            model_name='book',
            name='settings',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_settings', to='noveller.setting'),
        ),
        migrations.AlterField(
            model_name='book',
            name='target_audiences',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_audiences', to='noveller.targetaudience'),
        ),
        migrations.AlterField(
            model_name='book',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_themes', to='noveller.literarytheme'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_plots', to='noveller.book'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='events_of_plot',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.plotevent'),
        ),
        migrations.AlterField(
            model_name='plotevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plotevent',
            name='foreshadowing',
            field=models.ManyToManyField(blank=True, null=True, related_name='SubPlotEvent', to='noveller.plotevent'),
        ),
        migrations.AlterField(
            model_name='subplot',
            name='events_of_subplot',
            field=models.ManyToManyField(blank=True, null=True, related_name='subplots_events', to='noveller.subplotevent'),
        ),
    ]
