# Generated by Django 4.2 on 2023-04-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phusis', '0005_alter_phusisprojectattribute_name_and_more'),
        ('noveller', '0003_rename_orc_agent_set_objectives_book_orc_agent_set_goals_str_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='orc_agent_set_goals_str',
        ),
        migrations.AddField(
            model_name='book',
            name='agent_assignments_for_project',
            field=models.ManyToManyField(blank=True, default=[], related_name='projects_for_agent_assignment', to='phusis.agentassignment'),
        ),
        migrations.AlterField(
            model_name='book',
            name='goals_for_project',
            field=models.ManyToManyField(blank=True, default=[], to='phusis.phusisprojectgoal'),
        ),
    ]
