# Generated by Django 4.2 on 2023-04-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0004_alter_book_name_alter_book_project_local_directory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='script_for_project',
        ),
    ]
