# Generated by Django 4.2 on 2023-04-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0004_alter_book_chapters_alter_book_characters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_num',
            field=models.IntegerField(null=True),
        ),
    ]
