# Generated by Django 4.2 on 2023-04-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0004_book_storyevent_alter_book_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="appearance",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="noveller.appearance",
            ),
        ),
    ]
