# Generated by Django 4.2 on 2023-05-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0004_rename_chapterpartsummaryitem_chapterpartbreakdownitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteragent',
            old_name='awake',
            new_name='is_awake',
        ),
        migrations.RenameField(
            model_name='conflictandresolutionagent',
            old_name='awake',
            new_name='is_awake',
        ),
        migrations.RenameField(
            model_name='interdisciplinaryagent',
            old_name='awake',
            new_name='is_awake',
        ),
        migrations.RenameField(
            model_name='poeticsagent',
            old_name='awake',
            new_name='is_awake',
        ),
        migrations.RenameField(
            model_name='qualityevaluationagent',
            old_name='awake',
            new_name='is_awake',
        ),
        migrations.RenameField(
            model_name='researchagent',
            old_name='awake',
            new_name='is_awake',
        ),
        migrations.RenameField(
            model_name='sceneagent',
            old_name='awake',
            new_name='is_awake',
        ),
        migrations.RenameField(
            model_name='structuralagent',
            old_name='awake',
            new_name='is_awake',
        ),
        migrations.RenameField(
            model_name='themeexploringagent',
            old_name='awake',
            new_name='is_awake',
        ),
        migrations.RenameField(
            model_name='worldbuildingagent',
            old_name='awake',
            new_name='is_awake',
        ),
        migrations.RenameField(
            model_name='writingagent',
            old_name='awake',
            new_name='is_awake',
        ),
        migrations.RemoveField(
            model_name='characteragent',
            name='steps_taken',
        ),
        migrations.RemoveField(
            model_name='conflictandresolutionagent',
            name='steps_taken',
        ),
        migrations.RemoveField(
            model_name='interdisciplinaryagent',
            name='steps_taken',
        ),
        migrations.RemoveField(
            model_name='poeticsagent',
            name='steps_taken',
        ),
        migrations.RemoveField(
            model_name='qualityevaluationagent',
            name='steps_taken',
        ),
        migrations.RemoveField(
            model_name='researchagent',
            name='steps_taken',
        ),
        migrations.RemoveField(
            model_name='sceneagent',
            name='steps_taken',
        ),
        migrations.RemoveField(
            model_name='structuralagent',
            name='steps_taken',
        ),
        migrations.RemoveField(
            model_name='themeexploringagent',
            name='steps_taken',
        ),
        migrations.RemoveField(
            model_name='worldbuildingagent',
            name='steps_taken',
        ),
        migrations.RemoveField(
            model_name='writingagent',
            name='steps_taken',
        ),
        migrations.AddField(
            model_name='characteragent',
            name='model_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conflictandresolutionagent',
            name='model_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interdisciplinaryagent',
            name='model_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poeticsagent',
            name='model_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qualityevaluationagent',
            name='model_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='researchagent',
            name='model_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sceneagent',
            name='model_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='structuralagent',
            name='model_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='themeexploringagent',
            name='model_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='worldbuildingagent',
            name='model_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='writingagent',
            name='model_override',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
