# Generated by Django 4.2 on 2023-04-24 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0005_alter_chapter_chapter_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='distinguishing_features',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='eyes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='face',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='hair',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='backgroundresearch',
            name='deeper_research_topics',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.deeperbackgroundresearchtopic'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_characters', to='noveller.book'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='parts_for_chapter',
            field=models.ManyToManyField(blank=True, null=True, related_name='chapters', to='noveller.chapterpart'),
        ),
        migrations.AlterField(
            model_name='chapterpart',
            name='chapter_part_summary',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.chapterpartsummary'),
        ),
        migrations.AlterField(
            model_name='chapterpart',
            name='characters',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.characterversion'),
        ),
        migrations.AlterField(
            model_name='chapterpart',
            name='factions',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.faction'),
        ),
        migrations.AlterField(
            model_name='chapterpart',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.location'),
        ),
        migrations.AlterField(
            model_name='chapterpart',
            name='part_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chapterpart',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.literarytheme'),
        ),
        migrations.AlterField(
            model_name='chapterpartsummary',
            name='chapter_part_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapterpartsummary',
            name='pacing',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.pacing'),
        ),
        migrations.AlterField(
            model_name='chapterpartsummary',
            name='part_summary_items',
            field=models.ManyToManyField(blank=True, null=True, related_name='chapter_part_summary_items', to='noveller.chapterpartsummaryitem'),
        ),
        migrations.AlterField(
            model_name='chapterpartsummary',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.literarytheme'),
        ),
        migrations.AlterField(
            model_name='chapterpartsummaryitem',
            name='order_in_part',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='representative_of',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.literarytheme'),
        ),
        migrations.AlterField(
            model_name='character',
            name='versions',
            field=models.ManyToManyField(blank=True, null=True, related_name='version_of_character', to='noveller.characterversion'),
        ),
        migrations.AlterField(
            model_name='characterrelationship',
            name='age_started',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='characterrelationship',
            name='relationship_descriptors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='characterrelationship',
            name='relationship_from',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_relationship', to='noveller.characterversion'),
        ),
        migrations.AlterField(
            model_name='characterrelationship',
            name='relationship_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_relationship', to='noveller.characterversion'),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='beliefs',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.belief'),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='drives',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.drive'),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='fears',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.fear'),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='internal_conflicts',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.internalconflict'),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.location'),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='often_perceived_as',
            field=models.ManyToManyField(blank=True, null=True, related_name='often_perceived_as', to='noveller.charactertrait'),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='other_aspects',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_aspects', to='noveller.charactertrait'),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='strengths',
            field=models.ManyToManyField(blank=True, null=True, related_name='strengths', to='noveller.charactertrait'),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='version_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='weaknesses',
            field=models.ManyToManyField(blank=True, null=True, related_name='weaknesses', to='noveller.charactertrait'),
        ),
        migrations.AlterField(
            model_name='deeperbackgroundresearchtopic',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.characterversion'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='literaryinspirationperson',
            name='sources',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.literaryinspirationsource'),
        ),
        migrations.AlterField(
            model_name='litstyleguide',
            name='avoid',
            field=models.ManyToManyField(blank=True, null=True, related_name='litstyleguide_avoid', to='noveller.literarytrait'),
        ),
        migrations.AlterField(
            model_name='litstyleguide',
            name='imagery',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.literaryimagery'),
        ),
        migrations.AlterField(
            model_name='litstyleguide',
            name='inspirations',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.literaryinspirationperson'),
        ),
        migrations.AlterField(
            model_name='litstyleguide',
            name='perspective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noveller.narrativeperspective'),
        ),
        migrations.AlterField(
            model_name='litstyleguide',
            name='symbolism',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.literarysymbolism'),
        ),
        migrations.AlterField(
            model_name='litstyleguide',
            name='tone',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.literarytone'),
        ),
        migrations.AlterField(
            model_name='litstyleguide',
            name='traits',
            field=models.ManyToManyField(blank=True, null=True, related_name='litstyleguide_traits', to='noveller.literarytrait'),
        ),
        migrations.AlterField(
            model_name='location',
            name='character_versions',
            field=models.ManyToManyField(blank=True, null=True, related_name='locations_in_character_version', to='noveller.characterversion'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='background_events',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.backgroundevent'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.book'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='factions',
            field=models.ManyToManyField(blank=True, null=True, to='noveller.faction'),
        ),
    ]
