# Generated by Django 4.2 on 2023-04-11 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0005_book_appearance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="appearance",
        ),
        migrations.RemoveField(
            model_name="book",
            name="storyevent",
        ),
    ]
