# Generated by Django 4.2 on 2023-04-24 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0006_alter_appearance_distinguishing_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyteller',
            name='character_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noveller.characterversion'),
        ),
        migrations.AlterField(
            model_name='storyteller',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noveller.litstyleguide'),
        ),
    ]
