# Generated by Django 4.2 on 2023-04-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0006_rename_project_local_directory_book_project_workspace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='project_workspace',
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
