# Generated by Django 4.2 on 2023-04-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0006_remove_book_appearance_remove_book_storyevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="gender",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="origin",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="permanent_characteristics",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="sex",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="sexuality",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="characterrelatedsettingtopic",
            name="attitudes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="characterrelatedsettingtopic",
            name="food",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="characterrelatedsettingtopic",
            name="leisure",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="characterrelatedsettingtopic",
            name="rights",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="characterrelatedsettingtopic",
            name="social_life",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="characterrelatedsettingtopic",
            name="work",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="characterversion",
            name="age_at_end",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="characterversion",
            name="age_at_start",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
