# Generated by Django 4.2 on 2023-04-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0007_alter_character_gender_alter_character_origin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perspective",
            name="lit_style_guides",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perspectives",
                to="noveller.litstyleguide",
            ),
        ),
    ]
