# Generated by Django 4.2 on 2023-04-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0007_alter_storyteller_character_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storyteller',
            old_name='style',
            new_name='lit_style_guide',
        ),
    ]
