# Generated by Django 4.2 on 2023-04-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0008_rename_style_storyteller_lit_style_guide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterpartsummaryitem',
            options={'ordering': ['for_chapter_part_summary__for_chapter_part__for_chapter__book', 'for_chapter_part_summary__for_chapter_part__for_chapter__chapter_num', 'for_chapter_part_summary__for_chapter_part__part_num', 'order_in_part']},
        ),
        migrations.RenameField(
            model_name='chapterpartsummaryitem',
            old_name='for_chapter_part',
            new_name='for_chapter_part_summary',
        ),
    ]
