# Generated by Django 4.2 on 2023-04-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0008_alter_perspective_lit_style_guides"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapterpartsummaryitem",
            name="for_chapter_part_outline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="summary_items",
                to="noveller.chapterpartoutline",
            ),
        ),
    ]
