# Generated by Django 4.2 on 2023-04-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0009_alter_chapterpartsummaryitem_for_chapter_part_outline"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChapterPartOutline",
            new_name="ChapterPartSummary",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="chapter_outline",
        ),
        migrations.AlterField(
            model_name="chapterpart",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="noveller.chapter",
            ),
        ),
        migrations.DeleteModel(
            name="ChapterOutline",
        ),
    ]
