# Generated by Django 4.2 on 2023-04-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0009_alter_chapterpartsummaryitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapterpart',
            old_name='teller',
            new_name='storyteller',
        ),
    ]
