# Generated by Django 4.2 on 2023-04-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0010_rename_teller_chapterpart_storyteller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapterpart',
            old_name='characters',
            new_name='character_versions',
        ),
    ]
