# Generated by Django 4.2 on 2023-04-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0010_rename_chapterpartoutline_chapterpartsummary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapterpartsummary",
            name="summary_items",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chapter_part_summary",
                to="noveller.chapterpartsummaryitem",
            ),
        ),
        migrations.AlterField(
            model_name="chapterpartsummaryitem",
            name="for_chapter_part_outline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="noveller.chapterpartsummary",
            ),
        ),
    ]
