# Generated by Django 4.2 on 2023-04-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0011_rename_characters_chapterpart_character_versions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterversion',
            name='relationship_for',
        ),
        migrations.RemoveField(
            model_name='characterversion',
            name='relationship_with',
        ),
        migrations.AddField(
            model_name='characterversion',
            name='relationships',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noveller.characterrelationship'),
        ),
    ]
