# Generated by Django 4.2 on 2023-04-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0011_chapterpartsummary_summary_items_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapterpartsummary",
            name="summary_items",
        ),
        migrations.AddField(
            model_name="chapterpartsummary",
            name="summary_items",
            field=models.ManyToManyField(
                related_name="chapter_part_summary_items",
                to="noveller.chapterpartsummaryitem",
            ),
        ),
    ]
