# Generated by Django 4.2 on 2023-04-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noveller', '0012_remove_characterversion_relationship_for_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterversion',
            old_name='lit_style_guides',
            new_name='lit_style_guide',
        ),
    ]
