# Generated by Django 4.2 on 2023-04-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0012_remove_chapterpartsummary_summary_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapterpartsummaryitem",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
