# Generated by Django 4.2 on 2023-04-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0013_chapterpartsummaryitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapterpartsummaryitem",
            name="order",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
