# Generated by Django 4.2 on 2023-04-11 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0014_alter_chapterpartsummaryitem_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapterpartsummaryitem",
            old_name="order",
            new_name="order_in_part",
        ),
    ]
