# Generated by Django 4.2 on 2023-04-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0015_rename_order_chapterpartsummaryitem_order_in_part"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapterpart",
            name="location",
        ),
        migrations.AddField(
            model_name="chapterpart",
            name="location",
            field=models.ManyToManyField(blank=True, null=True, to="noveller.location"),
        ),
    ]
