# Generated by Django 4.2 on 2023-04-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0016_remove_chapterpart_location_chapterpart_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapterpart",
            name="location",
            field=models.ManyToManyField(blank=True, to="noveller.location"),
        ),
    ]
