# Generated by Django 4.2 on 2023-04-11 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0017_alter_chapterpart_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perspective",
            name="lit_style_guides",
        ),
    ]
