# Generated by Django 4.2 on 2023-04-11 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0018_remove_perspective_lit_style_guides"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="literarytraits",
            name="lit_style_guide_avoid",
        ),
        migrations.RemoveField(
            model_name="literarytraits",
            name="lit_style_guide_traits",
        ),
    ]
