# Generated by Django 4.2 on 2023-04-11 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0020_storyteller_chapter_parts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storyteller",
            name="chapter_parts",
        ),
    ]
