# Generated by Django 4.2 on 2023-04-11 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0021_remove_storyteller_chapter_parts"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="parts_for_chapter",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="chapters",
                to="noveller.chapterpart",
            ),
        ),
        migrations.AddField(
            model_name="chapterpart",
            name="for_chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapter_parts",
                to="noveller.chapter",
            ),
        ),
        migrations.AlterField(
            model_name="chapterpart",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="noveller.chapter",
            ),
        ),
    ]
