# Generated by Django 4.2 on 2023-04-11 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0022_chapter_parts_for_chapter_chapterpart_for_chapter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiteraryInspiration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("person", models.CharField(max_length=200)),
                ("source", models.CharField(max_length=200)),
                ("elaboration", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="litstyleguide",
            name="inspirations",
        ),
        migrations.AddField(
            model_name="litstyleguide",
            name="inspirations",
            field=models.ManyToManyField(
                blank=True, null=True, to="noveller.literaryinspiration"
            ),
        ),
    ]
