# Generated by Django 4.2 on 2023-04-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "noveller",
            "0024_literaryinspirationperson_literaryinspirationsource_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="literaryinspirationperson",
            name="sources",
            field=models.ManyToManyField(
                blank=True, null=True, to="noveller.literaryinspirationsource"
            ),
        ),
    ]
