# Generated by Django 4.2 on 2023-04-11 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0025_literaryinspirationperson_sources"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="literaryinspirationsource",
            name="person",
        ),
    ]
