# Generated by Django 4.2 on 2023-04-11 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0026_remove_literaryinspirationsource_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appearance",
            name="changes_from_previous_character_version",
        ),
        migrations.RemoveField(
            model_name="character",
            name="lit_style_guides",
        ),
        migrations.RemoveField(
            model_name="characterrelationship",
            name="changes_from_previous_version",
        ),
        migrations.RemoveField(
            model_name="characterversion",
            name="changes_from_previous_character_version",
        ),
        migrations.RemoveField(
            model_name="internalconflict",
            name="changes_from_previous_character_version",
        ),
        migrations.DeleteModel(
            name="ChangesFromPreviousCharacterVersion",
        ),
    ]
