# Generated by Django 4.2 on 2023-04-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "noveller",
            "0027_remove_appearance_changes_from_previous_character_version_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="versions",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="+", to="noveller.characterversion"
            ),
        ),
    ]
