# Generated by Django 4.2 on 2023-04-11 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0028_character_versions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="relationship_for",
        ),
        migrations.RemoveField(
            model_name="character",
            name="relationship_with",
        ),
        migrations.AddField(
            model_name="characterversion",
            name="relationship_for",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="noveller.characterrelationship",
            ),
        ),
        migrations.AddField(
            model_name="characterversion",
            name="relationship_with",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="noveller.characterrelationship",
            ),
        ),
        migrations.AlterField(
            model_name="characterrelationship",
            name="relationship_from",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="has_relationship",
                to="noveller.characterversion",
            ),
        ),
        migrations.AlterField(
            model_name="characterrelationship",
            name="relationship_to",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_relationship",
                to="noveller.characterversion",
            ),
        ),
    ]
