# Generated by Django 4.2 on 2023-04-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0029_remove_character_relationship_for_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="origin",
            field=models.TextField(blank=True, null=True),
        ),
    ]
