# Generated by Django 4.2 on 2023-04-12 04:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "noveller",
            "0032_genre_literaryimagery_literarymood_literarysymbolism_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plotevent",
            options={"ordering": ["order_in_story_events"]},
        ),
    ]
