# Generated by Django 4.2 on 2023-04-12 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("noveller", "0034_alter_appearance_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapterpartsummaryitem",
            options={
                "ordering": [
                    "for_chapter_part__for_chapter_part__chapter__book",
                    "for_chapter_part__for_chapter_part__chapter__chapter_num",
                    "for_chapter_part__for_chapter_part__part_num",
                    "order_in_part",
                ]
            },
        ),
        migrations.RenameField(
            model_name="chapterpartsummaryitem",
            old_name="for_chapter_part_outline",
            new_name="for_chapter_part",
        ),
    ]
