# Generated by Django 4.2 on 2023-04-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phusis", "0004_agentqualification_agenttrait_agent_elaboration_and_more"),
        ("noveller", "0036_alter_subplotevent_options_remove_plotevent_book_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="responsibilities",
            field=models.ManyToManyField(to="phusis.agent"),
        ),
    ]
