# Generated by Django 4.2 on 2023-04-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phusis", "0004_agentqualification_agenttrait_agent_elaboration_and_more"),
        ("noveller", "0037_book_responsibilities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="responsibilities",
            field=models.ManyToManyField(blank=True, null=True, to="phusis.agent"),
        ),
    ]
